---
- hosts: localhost
  gather_facts: false
  tasks:
    - debug: msg="name {{ name }}"
    - debug: msg="name {{ accounting }}"
    - debug: msg="name {{ item.firstName }}"
      loop: "{{ accounting }}"